https://www.youtube.com/watch?v=RwmhfIT8cvY

# INSTALL NUMPY

In [1]:
!pip install numpy

  Using cached numpy-2.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Using cached numpy-2.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.1 MB)


# IMPORT NUMPY SEBAGAI NP

In [2]:
import numpy as np

## CONTOH DATA

In [4]:
a = [12,23,34,45,56,67,78,89,101]

### SUM : Penjumlahan

In [5]:
print(np.sum(a))

505


### MEAN : Rata - Rata

In [6]:
print(np.mean(a))

56.111111111111114


### STD : RATA RATA JAUH ATAU MEAN YANG LEBIH HIGH LEVEL


**Standard deviation itu cuma cara untuk bilang:**

> “Seberapa jauh sih nilai-nilai ini dari rata-ratanya?”

---

#### 🎲 Misalnya kamu punya angka:

```
Data = [10, 20, 30]
```

Langkah-langkahnya:

---

#### 🧮 1. Cari rata-rata (mean)

$$
\text{mean} = (10 + 20 + 30) / 3 = 60 / 3 = 20
$$

---

#### 📏 2. Hitung “jarak” setiap angka dari rata-rata

| Angka | Jarak ke Mean | Jarak²       |
| ----- | ------------- | ------------ |
| 10    | 10 - 20 = -10 | (-10)² = 100 |
| 20    | 20 - 20 = 0   | 0² = 0       |
| 30    | 30 - 20 = 10  | 10² = 100    |

> Kenapa dikwadratkan? Karena kita nggak mau nilai minusnya saling meniadakan.

---

#### ➗ 3. Hitung rata-rata dari kuadrat jarak-jarak itu:

$$
(100 + 0 + 100) / 3 = 200 / 3 ≈ 66.67
$$

---

#### 📐 4. Ambil akar dari hasil itu:

$$
\sqrt{66.67} ≈ 8.16 ← inilah nilai **standard deviation**
$$

---


### SIN COS TAN TRIGONOMETRI

In [9]:
print(np.sin(a))

[-0.53657292 -0.8462204   0.52908269  0.85090352 -0.521551   -0.85551998
  0.51397846  0.86006941  0.45202579]


In [10]:
print(np.cos(a))

[ 0.84385396 -0.53283302 -0.84857027  0.52532199  0.85322011 -0.5177698
 -0.85780309  0.51017704  0.89200487]


In [11]:
print(np.tan(a))

[-0.63585993  1.58815308 -0.62349896  1.61977519 -0.61127369  1.65231726
 -0.59918     1.68582537  0.5067526 ]


### ARANGE, LINGSPACE, LOGSPACE

#### ✅ 1. `np.arange(start, stop, step)`

> Deretan angka dengan jarak tetap (step)

##### 🧪 Contoh-contoh:

```python
np.arange(0, 5, 1)
# Output: [0 1 2 3 4]

np.arange(5, 10, 2)
# Output: [5 7 9]

np.arange(0, 1, 0.2)
# Output: [0.  0.2 0.4 0.6 0.8]

np.arange(10, 0, -2)
# Output: [10  8  6  4  2]
```

##### ⚠️ Catatan:

* `stop` **tidak termasuk** hasil
* Cocok untuk **angka bulat** atau deret dengan step jelas

---

#### ✅ 2. `np.linspace(start, stop, num)`

> Deretan angka dengan jumlah titik tertentu, dibagi rata

##### 🧪 Contoh-contoh:

```python
np.linspace(0, 1, 5)
# Output: [0.   0.25 0.5  0.75 1.  ]

np.linspace(1, 10, 10)
# Output: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

np.linspace(5, 0, 6)
# Output: [5. 4. 3. 2. 1. 0.]

np.linspace(0, 100, 3)
# Output: [  0.  50. 100.]
```

##### ⚠️ Catatan:

* Termasuk angka `start` dan `stop`
* Cocok untuk grafik, interpolasi, atau pembagian rata

---

#### ✅ 3. `np.logspace(start, stop, num, base=10.0)`

> Deretan angka dalam **skala logaritmik** dari `base^start` ke `base^stop`

##### 🧪 Contoh-contoh:

```python
np.logspace(0, 3, 4)
# Output: [   1.   10.  100. 1000.]

np.logspace(1, 2, 5)
# Output: [ 10.          17.78        31.62        56.23       100.        ]

np.logspace(3, 0, 4)
# Output: [1000.  100.   10.    1.]

np.logspace(0.1, 1, 4, base=2)
# Output: [1.07  1.31  1.6   2.  ]  (basis 2)
```

##### ⚠️ Catatan:

* Cocok untuk data eksponensial, seperti frekuensi, skala ilmiah, grafik log
* Bisa ubah basis logaritma dengan argumen `base`

---

#### 🎯 Tips Pemakaian:

| Tujuan                      | Pakai Fungsi |
| --------------------------- | ------------ |
| Deret angka ber-step        | `arange()`   |
| Titik-titik dibagi rata     | `linspace()` |
| Skala logaritmik (eksponen) | `logspace()` |



## RANDOM

Sebuah array besar yang terdapat 2 array didalamnya dan masing masing array terdapat 9 angka random

In [22]:
np.random.rand(2,9)

array([[0.68241198, 0.14545359, 0.61179462, 0.52585172, 0.31128851,
        0.34325185, 0.05195829, 0.25765281, 0.41970636],
       [0.44586653, 0.49623074, 0.70838774, 0.54754946, 0.76162375,
        0.03281773, 0.21603033, 0.42474388, 0.3879634 ]])

In [24]:
np.random.rand(9,2)

array([[0.78815068, 0.13386565],
       [0.76155825, 0.96314679],
       [0.74247773, 0.33896396],
       [0.72862213, 0.00611243],
       [0.24082623, 0.24809516],
       [0.15385939, 0.90037318],
       [0.77817647, 0.43105534],
       [0.44352807, 0.49900148],
       [0.27660429, 0.53672416]])

Sebuah array besar yang terdapat 9 array didalamnya dan masing masing array terdapat 2 angka random

## CONTROLLED RANDOMNESS

In [27]:
state = np.random.RandomState(42)
state.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

#### ✅ Penjelasan Singkat:

### `np.random.RandomState` adalah **objek penghasil bilangan acak** lama di NumPy.

> Ini cara untuk **mengontrol atau mengulangi** hasil random — misalnya untuk testing atau eksperimen supaya hasil acaknya **tetap sama setiap dijalankan**.

---

#### 🧪 Contoh Penggunaan:


In [30]:
rng = np.random.RandomState(42)  # seed 42 → hasil acak jadi konsisten
print(rng.randint(0, 10, size=5))

[6 3 7 4 6]


Jika kamu ulang lagi baris itu, hasilnya akan **tetap sama** karena pakai seed `42`.

---

#### ⚠️ Kenapa Ada `RandomState`?

* Dulu (`NumPy < 1.17`), semua acakan pakai `RandomState`
* Sekarang lebih disarankan pakai:

  ```python
  rng = np.random.default_rng()
  ```

  Ini memakai **Generator** yang lebih baru dan lebih aman/statistiknya lebih baik.

---

#### 🔁 Perbandingan:

| Fitur                         | `RandomState`                  | `default_rng()` (baru) |
| ----------------------------- | ------------------------------ | ---------------------- |
| Versi lama                    | ✅ Digunakan sebelum NumPy 1.17 | ❌                      |
| Versi baru (direkomendasikan) | ❌                              | ✅ Sejak NumPy 1.17     |
| Tetap hasil acak (pakai seed) | ✅ Ya                           | ✅ Ya                   |

---

#### 🎯 Kapan Pakai?

* Kalau kamu pakai **kode lama**: mungkin masih pakai `RandomState`
* Kalau mulai proyek baru: **pakai `default_rng()`** saja


### Randint

In [34]:
np.random.randint(1,5)

2

In [ ]:
Data acak diantara 1 - 5